# Base image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

COPY  requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy the entire project into the container
COPY . . 

# Set PYTHONPATH environment variable
ENV PYTHONPATH=/app/src api_service_address=http://api_service:8080/api

# Expose the ports for the API and Gradio services
EXPOSE 8000

