# Base image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

COPY  requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy the entire project into the container
COPY . . 

# Set PYTHONPATH environment variable
ENV PYTHONPATH=/app/src

